version: '3.1'

services:
  elibrary:
    image: elibrary-spring-boot:latest
    build:
      context: .
    container_name: elibrary-spring-boot
    depends_on:
      - elibrary-mysql-data
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://elibrary-mysql-data:3306/by_it_academy_grodno_elibrary
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
    ports:
      - "8080:8080"

  elibrary-mysql-data:
    image: mysql:latest
    container_name: elibrary-mysql-data
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=by_it_academy_grodno_elibrary
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10