version: '3.1'

services:

#  elk:
#    image: sebp/elk
#    ports:
#      - "5601:5601"
#      - "9200:9200"
#      - "5044:5044"

  elk:
    image: elibrary-spring-boot-elk:latest
    build:
      context: elk
      dockerfile: Dockerfile
    ports:
      - "5601:5601"
      - "9200:9200"
      # Ports unused for access from the host so far
      #- "5044:5044"
      #- "4560:4560"

  elibrary:
    image: elibrary-spring-boot:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: elibrary-spring-boot
    depends_on:
      - elibrary-mysql-data
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://elibrary-mysql-data:3306/by_it_academy_grodno_elibrary
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
    ports:
      - "8080:8080"
    volumes:
      - app-logs:/logs

  elibrary-mysql-data:
    image: mysql:latest
    container_name: elibrary-mysql-data
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=by_it_academy_grodno_elibrary
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

volumes:
  app-logs: